### PR TITLE
feat: add issue lifecycle related metrics

### LINKED ISSUE #33: PR/Issue age Insights (need to differentiate by company)
## Feature Request

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Is your feature request related to a Issue or PR(Optional)

- Which project: 

- PR or Issue Link: 

### Describe the feature you'd like:

PR/Issue age Insights (need to differentiate by company).

### Do you have any ideas on how to implement it?(Optional)

### LINKED ISSUE #34: PR/Issue engagement Insight (needs to be differentiated by company)
## Feature Request

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Is your feature request related to a Issue or PR(Optional)

- Which project: 

- PR or Issue Link: 

### Describe the feature you'd like:

PR/Issue engagement Insight (needs to be differentiated by company)

### Do you have any ideas on how to implement it?(Optional)

### PR DESCRIPTION
**Pull request by Mini256**
Add new metrics:

- Issues age group by company
- Time to first comment on the issue group by company

Related issue:
close #34 
close #33

### CODE REVIEW

**Comment by Mini256** [comment]
preview:

- http://tikv.dev.devstats.tidb.io/d/issue-time-to-first-comment/issue-time-to-first-comment?orgId=1
- http://tikv.dev.devstats.tidb.io/d/11/issues-age-by-repository-group?orgId=1&from=now-90d&to=now-1w

I will refine the documentation in the next PR.

@hi-rustin PTAL~

**Comment by Mini256** [comment]
In the current data, the issue age of the top contributing company is longer than the not top, I think it is possible.
image

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
