### PR TITLE
feat: add affiliations sync cronjob

### PR DESCRIPTION
**Pull request by Mini256**
### Checked list

- [x] add import affiliation script
- [x] add affiliations sync cronjob
- [x] bump the version to 0.2.9

### Execution order

1. The cronjob invoke the `./shared/affs.sh` shell script
2. The `affs.sh` script will download the `github_users.json` that included the affiliation information
3. Use `shared/import_affs.sh` script import the the affiliation information to db
4. Use `shared/update_affs.sh` script rerun the metrics define in the metrics_affs.yaml file

### CODE REVIEW

**Comment by Mini256** [comment]
@hi-rustin  PTAL~

**Comment by Mini256** [comment]
@hi-rustin Is there anything else that needs to modify about this PR?

**Comment by hi-rustin** [comment]
> @hi-rustin Is there anything else that needs to modify about this PR?

No, but I'd like to take care of the current missing GitHub information we have before going on the prod environment. We can merge the PR, but don't run it on prod.

**Review by hi-rustin — APPROVED** [review]

**Comment by Mini256** [comment]
> No, but I'd like to take care of the current missing GitHub information we have before going on the prod environment. We can merge the PR, but don't run it on prod.

OK.

**Pull request merged**
