### PR TITLE
fix: refine pr opned/closed/merged metrics and dashbaords

### PR DESCRIPTION
**Pull request by Mini256**
I forgot to copy the metrics to prod and delete the redundant dashboard in the last PR.

### CODE REVIEW

**Comment by Mini256** [comment]
@hi-rustin PTAL~

The data is now correct:
https://tikv-devstats-dev.tidb.io/d/24/prs-merged-in-repository-groups?orgId=1&var-period=m&var-repogroup_name=All&var-repogroup=all

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
