### PR TITLE
feat: add active dashboards

### LINKED ISSUE #41: add active dashboard folder
## Feature Request

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Describe the feature you'd like:

Add active dashboard folder to contain dashboards which is important and mostly used.

### Do you have any ideas on how to implement it? (Optional)

### LINKED ISSUE #42: Refine the exclude selector name
## Bug Report

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### What is expected?

Refine the display text of the exclude selector.

### What is actually happening?

Currently, the display text of excludes selector has some problem.

### PR DESCRIPTION
**Pull request by Mini256**
close #42 
close #41

### CODE REVIEW

**Comment by Mini256** [comment]
preview:
image
image

**Comment by Mini256** [comment]
/unhold
@hi-rustin PTAL~

**Review by hi-rustin — APPROVED** [review]
Thanks!

**Pull request merged**
