### PR TITLE
feat: update grafana config to prod

### PR DESCRIPTION
**Pull request by Mini256**
Just copy the grafana config from dev to prod.

### CODE REVIEW

**Comment by Mini256** [comment]
@hi-rustin PTAL~

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
What a big PR.  🤣

**Comment by Mini256** [comment]
> What a big PR. 🤣

This is the accumulated update on dev. It seems that separating this part of the configuration files that should be shared will bring us some trouble. For example, after the pod image is updated, should we test the prod image on dev? However, we still need to do some development on dev.

**Pull request merged**
