### PR TITLE
fix: refine the icon and the country label

### PR DESCRIPTION
**Pull request by Mini256**

### CODE REVIEW

**Comment by Mini256** [comment]
/hold

Wait test with image `miniantdev/xxx-dev:0.1.0`

**Comment by Mini256** [comment]
Already test with image `miniantdev/devstats-dev:0.1.1`

**Review by hi-rustin — COMMENTED** [review]
LGTM.

But should we use the pingcap logo instead of the tidb?

**Comment by Mini256** [comment]
> But should we use the pingcap logo instead of the tidb?

The icon of pingcap has been added, but it didn't seem to work after modifying the values.yaml file. Maybe we need to modify 
`change_ title_ and_ icons.sh `.

Maybe we can change the configuration of tidb to pingcap in the next pr.

**Pull request merged**
