### PR TITLE
 feat: add not-pingcap filter option and chart

### PR DESCRIPTION
**Pull request by Mini256**
Preview：

image

http://pingcap.dev.devstats.tidb.io/d/66/developer-activity-counts-by-companies?orgId=1

### CODE REVIEW

**Comment by Mini256** [comment]
/hold
wait to build image to test

**Comment by Mini256** [comment]
/unhold

@hi-rustin PTAL~ Thanks

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
I still think not pingcap would be weird.

**Comment by Mini256** [comment]
> I still think not pingcap would be weird.

There seems to be no radio box variable component on grafana, so I added "not pingcap" to the companies list instead. Do you have any ideas about this display name?

**Comment by hi-rustin** [comment]
> so I added "not pingcap" to the companies list instead. Do you have any ideas about this display name?

In my opinion, it makes sense to use its own select all and then unpingcap. not pingcap is very strange from a UX point of view, although it can count more.

**Comment by Mini256** [comment]
I have add a "exclude pingcap" selector to realize the screening function of external contributors. 

When exclude_pingcap is true, the "PingCAP" option will be removed from the Companies option list, and the query result will only display contributor data other than PingCAPer.

@hi-rustin  PTAL~

**Comment by hi-rustin** [comment]
> When exclude_pingcap is true, the "PingCAP" option will be removed from the Companies option list, and the query result will only display contributor data other than PingCAPer.

Cool! Thanks!

**Pull request merged**
