### PR TITLE
feat: add dev configuration

### PR DESCRIPTION
**Pull request by Mini256**
Please refer to the file directory structure：https://github.com/Mini256/devstats/tree/mini256-patch

Review `build_images.sh` script mainly.

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
I will review it tomorrow or Monday.

**Comment by Mini256** [comment]
There are still some problems here, I found that `devel/depoly_all.sh` is somewhat different from `example/depoly_all.sh` under devstats-docker-image repo.

**Pull request merged**
