### PR TITLE
feat: add company group for pr lifecycle related metrics

### PR DESCRIPTION
**Pull request by Mini256**
Add external group for the following metrics:

- PR opened to merged group by company
- Time metrics group by company
- PR first non-author activity group by company
- PR age group by company

### CODE REVIEW

**Comment by Mini256** [comment]
/hold
Waiting for test on dev

**Comment by Mini256** [comment]
@hi-rustin PTAL~

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
/merge

Good job!

**Pull request merged**
